#!/bin/bash

######################
### Upload Script ####
######################
### Version 0.92 ###
######################

####### EDIT ONLY THESE SETTINGS #######

# INSTRUCTIONS
# 1. Edit the change the name of the rclone remote and local share to match your setup
# 2. NOTE: enter RcloneRemoteName WITHOUT ':'
# 3. Optional: include bind mount settings for potential traffic shaping/monitoring
# 4. Optional: use multiple remotes to get extra upload quota of (number of remotes) x 750GB/day e.g to max out a 1Gbps line 14-15 remotes would be needed

# REQUIRED SETTINGS
RcloneCommand="move" # choose your rclone command e.g. move, copy, sync
RcloneRemoteName="gdrive_vfs" # Name of rclone remote mount WITHOUT ':'. NOTE: Choose your encrypted remote for sensitive data
RcloneUploadRemoteName="gdrive_vfs" # If you have a second remote created for uploads put it here.  Otherwise use the same remote as RcloneRemoteName
LocalFilesShare="/mnt/user/local" # location of the local files you want to upload without trailing slash to rclone e.g. /mnt/user/local
RcloneMountShare="/mnt/user/mount_rclone" # where your rclone remote will be located without trailing slash  e.g. /mnt/user/mount_rclone

# Note: Again - remember to NOT use ':' in your remote name above

# Bandwidth limits: specify the desired bandwidth in kBytes/s, or use a suffix b|k|M|G. Or 'off' or '0' for unlimited.  The script now uses --drive-stop-on-upload-limit which stops the script if the 750GB/day limir is achieved, so you no loger have to slow 'trickle' your files all day if you don't want to e.g. could just do an unlimited job overnight.
BWLimit1="off"
BWLimit1Time="01:00"
BWLimit2="15M"
BWLimit2Time="08:00"
BWLimit3="12M"
BWLimit3Time="16:00"

# OPTIONAL SETTINGS

# Bind the mount to an IP address
CreateBindMount="Y" # Y/N. Choose whether to bind traffic to a particular network adapter
RCloneMountIP="172.30.12.22" # My unraid IP is 172.30.12.2 so I create another similar IP address
NetworkAdapter="eth0" # choose your network adapter. eth0 recommended
VirtualIPNumber="2" # creates eth0:x e.g. eth0:1.  I create a unique virtual IP addresses for each mount & upload so I can monitor and traffic shape for each of them

# Use Multiple upload remotes for multiple quotas
UseMultipleUploadRemotes="Y" # Y/N. Choose whether want to rotate multiple upload remotes for incresed quota (750GB x number of remotes)
RemoteNumber="15" # Integer number of remotes to use.  
RcloneUploadRemoteStart="gdrive_counter" # Enter characters before counter in your remote names ## i.e. for gdrive_counter1_vfs, gdrive_counter2_vfs, ...gdrive_counter15_vfs,gdrive_counter16_vfs enter 'gdrive_counter'
RcloneUploadRemoteEnd="_vfs" # Enter characters after counter ## i.e. for gdrive_counter1_vfs, gdrive_counter2_vfs, ...gdrive_counter15_vfs,gdrive_counter16_vfs enter '_vfs'

####### END SETTINGS #######

###############################################################################
#####    DO NOT EDIT BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING   #####
###############################################################################

####### Preparing mount location variables #######
LocalFilesLocation="$LocalFilesShare/$RcloneRemoteName" # Location for local files to be merged with rclone mount
RcloneMountLocation="$RcloneMountShare/$RcloneRemoteName" # Location for rclone mount

####### create directories for rclone mount and mergerfs mounts #######
mkdir -p /mnt/user/appdata/other/rclone/$RcloneRemoteName #for script files

#######  Check if script already running  ##########
echo "$(date "+%d.%m.%Y %T") INFO: *** Starting rclone_upload script for ${RcloneRemoteName} ***"
if [[ -f "/mnt/user/appdata/other/rclone/$RcloneRemoteName/upload_running" ]]; then
	echo "$(date "+%d.%m.%Y %T") INFO: Exiting as script already running."
	exit
else
	echo "$(date "+%d.%m.%Y %T") INFO: Script not running - proceeding."
	touch /mnt/user/appdata/other/rclone/$RcloneRemoteName/upload_running
fi

#######  check if rclone installed  ##########
echo "$(date "+%d.%m.%Y %T") INFO: Checking if rclone installed successfully."
if [[ -f "$RcloneMountLocation/mountcheck" ]]; then
	echo "$(date "+%d.%m.%Y %T") INFO: rclone installed successfully - proceeding with upload."
else
	echo "$(date "+%d.%m.%Y %T") INFO: rclone not installed - will try again later."
	rm /mnt/user/appdata/other/rclone/$RcloneRemoteName/upload_running
	exit
fi

####### Adjusting RcloneUploadRemoteName if using multiple remotes #######
if [[  $UseMultipleUploadRemotes == 'Y' ]]; then
	CounterNumber=$(find /mnt/user/appdata/other/rclone/$RcloneRemoteName/ -name 'counter_*' | cut -d"_" -f3)
	echo $CounterNumber
	CounterCheck="1"
	if [[ "$CounterNumber" -ge "$CounterCheck" ]];then
		echo "$(date "+%d.%m.%Y %T") INFO: Counter file found for ${RcloneRemoteName}."
	else
		echo "$(date "+%d.%m.%Y %T") INFO: No counter file found for ${RcloneRemoteName}. Creating counter_1."
		touch /mnt/user/appdata/other/rclone/$RcloneRemoteName/counter_1
	fi
# creating new $RcloneUploadRemoteName based on counter
	RcloneUploadRemoteName=$RcloneUploadRemoteStart
	RcloneUploadRemoteName+=$CounterNumber
	RcloneUploadRemoteName+=$RcloneUploadRemoteEnd
	echo "$(date "+%d.%m.%Y %T") INFO: Adjusted upload remote name to ${RcloneUploadRemoteName} based on counter ${CounterNumber}."
else
	echo "$(date "+%d.%m.%Y %T") INFO: Uploading using one remote"
fi

#######  Upload files  ##########

if [[  $CreateBindMount == 'Y' ]]; then
# upload with bind option
	echo "$(date "+%d.%m.%Y %T") INFO: *** Checking if IP address ${RCloneMountIP} already created for upload to remote ${RcloneRemoteName}"
	ping -q -c2 $RCloneMountIP > /dev/null # -q quiet, -c number of pings to perform
	if [ $? -eq 0 ]; then # ping returns exit status 0 if successful
		echo "$(date "+%d.%m.%Y %T") INFO: *** IP address ${RCloneMountIP} already created for upload to remote ${RcloneRemoteName}"
	else
		echo "$(date "+%d.%m.%Y %T") INFO: *** Creating IP address ${RCloneMountIP} for upload to remote ${RcloneRemoteName}"
		ip addr add $RCloneMountIP/24 dev $NetworkAdapter label $NetworkAdapter:$VirtualIPNumber
	fi
	echo "$(date "+%d.%m.%Y %T") INFO: *** Using IP address ${RCloneMountIP} to upload to remote ${RcloneRemoteName}"
	rclone $RcloneCommand $LocalFilesLocation $RcloneUploadRemoteName: \
	--user-agent="$RcloneUploadRemoteName" \
	-vv \
	--buffer-size 512M \
	--drive-chunk-size 512M \
	--tpslimit 8 \
	--checkers 8 \
	--transfers 4 \
	--order-by modtime,ascending \
	--min-age 10m \
	--exclude .Recycle.Bin/** \
	--exclude downloads/** \
	--exclude *fuse_hidden* \
	--exclude *_HIDDEN \
	--exclude .recycle** \
	--exclude *.backup~* \
	--exclude *.partial~* \
	--delete-empty-src-dirs \
	--drive-stop-on-upload-limit \
	--bwlimit "${BWLimit1Time},${BWLimit1} ${BWLimit2Time},${BWLimit2} ${BWLimit3Time},${BWLimit3}" \
	--bind=$RCloneMountIP
# upload without bind option
else
	echo "$(date "+%d.%m.%Y %T") INFO: *** Uploading to remote ${RcloneRemoteName}"
	rclone $RcloneCommand $LocalFilesLocation $RcloneUploadRemoteName: \
	--user-agent="$RcloneUploadRemoteName" \
	-vv \
	--buffer-size 512M \
	--drive-chunk-size 512M \
	--tpslimit 8 \
	--checkers 8 \
	--transfers 4 \
	--order-by modtime,ascending \
	--min-age 10m \
	--exclude .Recycle.Bin/** \
	--exclude downloads/** \
	--exclude *fuse_hidden* \
	--exclude *_HIDDEN \
	--exclude .recycle** \
	--exclude *.backup~* \
	--exclude *.partial~* \
	--delete-empty-src-dirs \
	--drive-stop-on-upload-limit \
	--bwlimit "${BWLimit1Time},${BWLimit1} ${BWLimit2Time},${BWLimit2} ${BWLimit3Time},${BWLimit3}" 
fi

#######  Remove Control Files  ##########

# update counter and remove other control files
if [[  $UseMultipleUploadRemotes == 'Y' ]]; then
	if [[ "$CounterNumber" == "$RemoteNumber" ]];then
		rm /mnt/user/appdata/other/rclone/$RcloneRemoteName/counter_$CounterNumber
		touch /mnt/user/appdata/other/rclone/$RcloneRemoteName/counter_1
		echo "$(date "+%d.%m.%Y %T") INFO: Final counter used - resetting loop and created counter_1."
		CounterNumber=$(find /mnt/user/appdata/other/rclone/$RcloneRemoteName/ -name 'counter_*' | cut -d"_" -f3)
	else
		rm /mnt/user/appdata/other/rclone/$RcloneRemoteName/counter_$CounterNumber
		CounterNumber=$((CounterNumber+1))
		touch /mnt/user/appdata/other/rclone/$RcloneRemoteName/counter_$CounterNumber
		echo "$(date "+%d.%m.%Y %T") INFO: Created counter_${CounterNumber} for next upload run."
	fi
else
	echo "$(date "+%d.%m.%Y %T") INFO: Not utilising multiple upload remotes."
fi

# remove dummy file
rm /mnt/user/appdata/other/rclone/$RcloneRemoteName/upload_running
echo "$(date "+%d.%m.%Y %T") INFO: Script complete"

exit
