#!/bin/bash

######################
### Cleanup Script ####
######################
#### Version 0.9 #####
######################

echo "$(date "+%d.%m.%Y %T") INFO: *** Starting rclone_cleanup script ***"

####### Cleanup Tracking Files #######

echo "$(date "+%d.%m.%Y %T") INFO: *** Removing Tracking Files ***"

rm -r /mnt/user/appdata/other/rclone/

echo "$(date "+%d.%m.%Y %T") INFO: ***Finished Cleanup! ***"

exit
