#!/bin/bash

#############################################################################
######################           User Config           ######################
######################          Creator Script         ######################
#############################################################################

configfile="/mnt/user/appdata/other/rclone/config.cfg" #Location to create config file. Leave as default unless you need to run multiple mount/upload scripts

overwrite_protection="y" #Options - "y/n". Setting to "n" will allow this script to overwrite prior user config files if present at location above (configfile=XXXXX)


#############################################################################
########################      ------------------      #######################
#############################################################################
########################          ----------          #######################
########################       Required Mount         #######################
########################           Settings           #######################
########################          ----------          #######################
#############################################################################
########################      ------------------      #######################
#############################################################################

RcloneRemoteName="gcrypt" # Name of rclone remote mount WITHOUT ':'. NOTE: Choose your encrypted remote for sensitive data
RcloneMountShare="/mnt/user/mount_rclone" # where your rclone remote will be located without trailing slash  e.g. /mnt/user/mount_rclone
MergerfsMountShare="/mnt/user/mount_mergerfs" # location without trailing slash  e.g. /mnt/user/mount_mergerfs. Enter 'ignore' to disable
DockerStart="plex ombi sonarr radarr tautulli nzbget" # list of dockers, separated by space, to start once mergerfs mount verified. Remember to disable AUTOSTART for dockers added in docker settings page
LocalFilesShare="/mnt/user/local" # location of the local files and MountFolders you want to upload without trailing slash to rclone e.g. /mnt/user/local. Enter 'ignore' to disable
loglevel="NOTICE" # Log Level: (DEBUG, INFO, NOTICE, ERROR). Default is NOTICE which will show large events, warnings, errors. DEBUG is useful if you are having issues. 
MountFolders={downloads/{complete,intermediate,seeds},movies,tv} # comma separated list of folders to create within the mount

#############################################################################
########################          ----------          #######################
########################   Optional MOUNT Settings    #######################
########################          ----------          #######################
#############################################################################

#############################################################################
###################      Custom Rclone MOUNT Commands     ###################
#############################################################################

Command1_mount=""
Command2_mount=""
Command3_mount=""
Command4_mount=""
Command5_mount=""
Command6_mount=""
Command7_mount=""
Command8_mount=""

#############################################################################
###################       Additional Local Shares to      ###################
###################          be added with MergerFS       ###################
#############################################################################

LocalFilesShare2="ignore" # without trailing slash e.g. /mnt/user/other__remote_mount/or_other_local_folder.  Enter 'ignore' to disable
LocalFilesShare3="ignore"
LocalFilesShare4="ignore"

#############################################################################
######################    Bind Mount to Unique IP      ######################
#############################################################################

CreateBindMount_mount="N" # Y/N. Choose whether to bind traffic to a particular network adapter
RCloneMountIP_mount="192.168.1.252" # My unraid IP is 172.30.12.2 so I create another similar IP address
NetworkAdapter_mount="eth0" # choose your network adapter. eth0 recommended
VirtualIPNumber_mount="2" # creates eth0:x e.g. eth0:1.  I create a unique virtual IP addresses for each mount & upload so I can monitor and traffic shape for each of them



#############################################################################
########################      ------------------      #######################
#############################################################################
########################          ----------          #######################
########################       Required Upload        #######################
########################           Settings           #######################
########################          ----------          #######################
#############################################################################
########################      ------------------      #######################
#############################################################################

RcloneCommand="move" # choose your rclone upload command. Options: move, copy, sync.
RcloneUploadRemoteName="gcrypt" # If you have a second remote created for uploads put it here.  Otherwise use the same remote as RcloneRemoteName in the Mount settings above.
MinimumAge="15m" # sync files suffix ms|s|m|h|d|w|M|y *Ignored and uses default 15m with Beta GUI due to known Rclone bug*
ModSort="ascending" # "ascending" oldest files first, "descending" newest files first

#############################################################################
########################          ----------          #######################
########################   Optional Upload Settings   #######################
########################          ----------          #######################
#############################################################################

#############################################################################
########################     Add Upload Job Name      #######################
#############################################################################

JobName="_daily_upload" # Adds custom string to end of checker file.  Useful if you're running multiple jobs against the same remote. Not applicable with webgui enabled

#############################################################################
##############                Bandwidth Limits?                ##############
##############  Suffix b|k|M|G. Or 'off' or '0' for Unlimited  ##############
# The script uses --drive-stop-on-upload-limit which stops the script if    #
# the 750GB/day limit is achieved, so you no longer have to slow 'trickle'  #
# your files all day if you don't want to e.g. could just do an unlimited   #
# job overnight.                                                            #
#############################################################################

BWLimit1Time="01:00"
BWLimit1="off"
BWLimit2Time="08:00"
BWLimit2="off"
BWLimit3Time="16:00"
BWLimit3="off"

#############################################################################
###################     Custom Rclone UPLOAD Commands     ###################
#############################################################################

Command1_upload=""
Command2_upload=""
Command3_upload=""
Command4_upload=""
Command5_upload=""
Command6_upload=""
Command7_upload=""
Command8_upload=""

#############################################################################
###########               Bind Upload to Unique IP                ###########
#############################################################################

CreateBindMount_upload="N" # Y/N. Choose whether or not to bind traffic to a network adapter.
RCloneMountIP_upload="192.168.1.253" # Choose IP to bind upload to.
NetworkAdapter_upload="eth0" # choose your network adapter. eth0 recommended.
VirtualIPNumber_upload="1" # creates eth0:x e.g. eth0:1.

#############################################################################
#############            Service Accounts for Upload           ##############
#############   Guide: https://github.com/xyou365/AutoRclone   ##############
#############################################################################

UseServiceAccountUpload="Y" # Y/N. Choose whether to use Service Accounts.
ServiceAccountDirectory="/mnt/user/appdata/other/rclone/service_accounts" # Path to your Service Account's .json files.
ServiceAccountFile="sa_gdrive_upload" # Enter characters before counter in your json files e.g. for sa_gdrive_upload1.json, sa_gdrive_upload2.json, ect: enter "sa_gdrive_upload".
CountServiceAccounts="99" # Integer number of service accounts to use.


#############################################################################
######################      Is this a Backup Job?      ######################
#############################################################################

BackupJob="N" # Y/N. Syncs or Copies files from LocalFilesLocation to BackupRemoteLocation, rather than moving from LocalFilesLocation/RcloneRemoteName
BackupRemoteLocation="backup" # choose location on mount for deleted sync files
BackupRemoteDeletedLocation="backup_deleted" # choose location on mount for deleted sync files
BackupRetention="90d"  #How long to keep deleted sync files suffix ms|s|m|h|d|w|M|y

#############################################################################
#############################################################################
######################       END OF USER SETTINGS      ######################
#############################################################################
#############################################################################



####################        Create config File         ####################

mkdir -p /mnt/user/appdata/other/rclone/

if [[ -f $configfile ]]; then
	echo "$(date "+%d.%m.%Y %T") Warning: Config file already present."
		if [[ $overwrite_protection == "y" ]]; then
			echo "$(date "+%d.%m.%Y %T") Warning: Overwrite Protection Enabled. Please modify the script settings or delete prior config"
			exit
		else
			echo "$(date "+%d.%m.%Y %T") Info: Overwrite Protection Disabled. New user config will overwrite file"
		fi
fi	
		echo "$(date "+%d.%m.%Y %T") Info: Writing user config to $configfile."
		cat <<-EOF > $configfile
		RcloneRemoteName="$RcloneRemoteName"
		RcloneMountShare="$RcloneMountShare"
		MergerfsMountShare="$MergerfsMountShare"
		DockerStart="$DockerStart"
		LocalFilesShare="$LocalFilesShare"
		MountFolders=$MountFolders
		
		Webgui="$Webgui"
		Webgui_Username="$Webgui_Username"
		Webgui_Password="$Webgui_Password"
		Webgui_Address="$Webgui_Address"
		Exclusionfilter1="$Exclusionfilter1"
		Exclusionfilter2="$Exclusionfilter2"
		
		Command1_mount="$Command1_mount"
		Command2_mount="$Command2_mount"
		Command3_mount="$Command3_mount"
		Command4_mount="$Command4_mount"
		Command5_mount="$Command5_mount"
		Command6_mount="$Command6_mount"
		Command7_mount="$Command7_mount"
		Command8_mount="$Command8_mount"
		
		
		LocalFilesShare2="$LocalFilesShare2" 
		LocalFilesShare3="$LocalFilesShare3"
		LocalFilesShare4="$LocalFilesShare4"
		
		
		CreateBindMount_mount="$CreateBindMount_mount"
		RCloneMountIP_mount="$RCloneMountIP_mount"
		NetworkAdapter_mount="$NetworkAdapter_mount"
		VirtualIPNumber_mount="$VirtualIPNumber_mount"
		
		RcloneCommand="$RcloneCommand"
		RcloneUploadRemoteName="$RcloneUploadRemoteName"
		MinimumAge="$MinimumAge"
		ModSort="$ModSort"
		
		JobName="$JobName"
		
		BWLimit1Time="$BWLimit1Time"
		BWLimit1="$BWLimit1"
		BWLimit2Time="$BWLimit2Time"
		BWLimit2="$BWLimit2"
		BWLimit3Time="$BWLimit3Time"
		BWLimit3="$BWLimit3"
		
		Command1_upload="$Command1_upload"
		Command2_upload="$Command2_upload"
		Command3_upload="$Command3_upload"
		Command4_upload="$Command4_upload"
		Command5_upload="$Command5_upload"
		Command6_upload="$Command6_upload"
		Command7_upload="$Command7_upload"
		Command8_upload="$Command8_upload"
		
		
		CreateBindMount_upload="$CreateBindMount_upload"
		RCloneMountIP_upload="$RCloneMountIP_upload"
		NetworkAdapter_upload="$NetworkAdapter_upload"
		VirtualIPNumber_upload="$VirtualIPNumber_upload"
		
		UseServiceAccountUpload="$UseServiceAccountUpload"
		ServiceAccountDirectory="$ServiceAccountDirectory"
		ServiceAccountFile="$ServiceAccountFile"
		CountServiceAccounts="$CountServiceAccounts"
		
		ServiceAccountRemoteName="$ServiceAccountRemoteName"
		ServiceAccountCryptName="$ServiceAccountCryptName"
		
		BackupJob="$BackupJob"
		BackupRemoteLocation="$BackupRemoteLocation"
		BackupRemoteDeletedLocation="$BackupRemoteDeletedLocation"
		BackupRetention="$BackupRetention"	
		
		EOF

if [[ -f $configfile ]]; then
	echo "$(date "+%d.%m.%Y %T") Info: User config successfully written to $configfile"
	else
	echo "$(date "+%d.%m.%Y %T") Error: Couldn't write user config to $configfile"
fi

exit