#!/bin/bash

# Make sure we're working on torrents.
if [[ "${sonarr_episodefile_sourcepath}" == *"torrents"* ]]; then
	echo "[Torrent Symlink] Path ${sonarr_episodefile_sourcepath} contains \"torrents\"."

	# Make sure destination path is media not rclone upload
	if [[ "${sonarr_episodefile_path}"  == *"media"* ]]; then
		echo "[Torrent Symlink] Path ${sonarr_episodefile_path} contains \"media\", exiting."
	else
		exit
	fi

else
  exit
fi

# If the source file doesn't exist, error out.
if ! [[ -f "${sonarr_episodefile_sourcepath}" ]]; then
  echo "[Torrent Symlink] File ${sonarr_episodefile_sourcepath} does not exist, exiting."
  exit 1
fi

sleep 1

# Make sure the copy is done by comparing source and destination file sizes.
ORIGFILESIZE=$(stat -c%s "${sonarr_episodefile_sourcepath}")
PERMFILESIZE=$(stat -c%s "${sonarr_episodefile_path}")

sleep 30

while [[ $PERMFILESIZE != $ORIGFILESIZE ]]; do
    sleep 60
    PERMFILESIZE=$(stat -c%s "$PERMPATH")
done

# Make the actual symlink.
if [[ $PERMFILESIZE == $ORIGFILESIZE ]]; then
    rm "$LINKPATH"
    ln -s "$PERMPATH" "$LINKPATH"
fi

exit
