#!/bin/bash

#######################
###  Terminate RC  ####
#######################
###  Version 0.1.0 ####
#######################

configfile="/mnt/user/appdata/other/rclone/config.cfg" #Leave as default unless you need to run multiple configs. Example - multiple mount/upload scripts


######################       END OF USER SETTINGS       #####################

######################  Load and Prep Config Variables  #####################

if [[ -f "$configfile" ]]; then
		echo "$(date "+%d.%m.%Y %T") INFO: Found Config Files"
	else
		echo "$(date "+%d.%m.%Y %T") ERROR: No Config File found."
		echo "$(date "+%d.%m.%Y %T") ERROR: Please edit config file at /mnt/user/appdata/other/rclone/config.cfg."
		exit
fi

echo "$(date "+%d.%m.%Y %T") INFO: Loading Config File."

shopt -s extglob
tr -d '\r' < $configfile > $config.cfg
while IFS='= ' read -r lhs rhs
do
    if [[ ! $lhs =~ ^\ *# && -n $lhs ]]; then
        rhs="${rhs%%\#*}"    # Del in line right comments
        rhs="${rhs%%*( )}"   # Del trailing spaces
        rhs="${rhs%\"*}"     # Del opening string quotes 
        rhs="${rhs#\"*}"     # Del closing string quotes 
        declare $lhs="$rhs"
    fi
done < $config.cfg



####### Script #######
Webguicommands="--rc-user=$Webgui_Username --rc-pass=$Webgui_Password --rc-addr=$Webgui_Address"
echo "$(date "+%d.%m.%Y %T") INFO: *** Terminating Rclone Mount and RC ***"

rclone rc $Webguicommands core/quit

exit
